spring:
  application:
    name:
      API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    config:
      profile: dev
  config:
    import: configserver:http://localhost:8888
