spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/inventorydb?createDatabaseIfNotExist=true
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            javax:
                persistence:
                    validation:
                        mode: none
        hibernate:
            ddl-auto: update