spring:
    application:
        name: INVENTORY-SERVICE
    datasource:
        url: jdbc:postgresql://localhost:5432/inventorydb?createDatabaseIfNotExist=true
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update

server:
    port: 0

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}
        prefer-ip-address: true